/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

clientsClaim();
self.skipWaiting();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute([{"revision":"efe686e7b9630f85377aad1ce5f89b4a","url":"fonts/DMSans/DMSans-Bold.eot"},{"revision":"831ba79641cdef5c258181ff5904e90e","url":"fonts/DMSans/DMSans-Bold.svg"},{"revision":"12d055270b42bedac8407d8470d72f62","url":"fonts/DMSans/DMSans-Bold.ttf"},{"revision":"41dc91eef0c4c43e6907b9d75518a270","url":"fonts/DMSans/DMSans-Bold.woff"},{"revision":"b316fb907e868e12a20113ac1e81a214","url":"fonts/DMSans/DMSans-Bold.woff2"},{"revision":"0e8b934b7b1245560e78075aab062ae3","url":"fonts/DMSans/DMSans-BoldItalic.eot"},{"revision":"0397759ae7a03d9cc5fd21a65e7384b5","url":"fonts/DMSans/DMSans-BoldItalic.svg"},{"revision":"38f4b7112142bb4823d620976cf55ceb","url":"fonts/DMSans/DMSans-BoldItalic.ttf"},{"revision":"f303dd565afe6cf64d2ec80da20969c1","url":"fonts/DMSans/DMSans-BoldItalic.woff"},{"revision":"267e76a132c7f2b8119f25ba417ff675","url":"fonts/DMSans/DMSans-BoldItalic.woff2"},{"revision":"8f02c19bfa7668cf5ff9f0dc861f0825","url":"fonts/DMSans/DMSans-Italic.eot"},{"revision":"e36e681160231669e90b52e939340692","url":"fonts/DMSans/DMSans-Italic.svg"},{"revision":"8c574cf34eb13a30b7eb03e435a563a4","url":"fonts/DMSans/DMSans-Italic.ttf"},{"revision":"263ef58d3975bdd051559a59f68f8ed3","url":"fonts/DMSans/DMSans-Italic.woff"},{"revision":"a400a3fbf03e095d1c17df30e963fb90","url":"fonts/DMSans/DMSans-Italic.woff2"},{"revision":"af17a5c8ed7f06bb425fc1c85ff466f4","url":"fonts/DMSans/DMSans-Medium.eot"},{"revision":"a83565b689ffbc17175e8eae296d5f72","url":"fonts/DMSans/DMSans-Medium.svg"},{"revision":"d60313e410313f624d7c44ebaafc3e84","url":"fonts/DMSans/DMSans-Medium.ttf"},{"revision":"bbd54ab4920d4816e2874306205565cb","url":"fonts/DMSans/DMSans-Medium.woff"},{"revision":"d940ea16273447cce854f545842768fe","url":"fonts/DMSans/DMSans-Medium.woff2"},{"revision":"62de8ae86752830d33f455e8b34bfd90","url":"fonts/DMSans/DMSans-MediumItalic.eot"},{"revision":"6badd392fb1e2aa5c5d6e28e61f92096","url":"fonts/DMSans/DMSans-MediumItalic.svg"},{"revision":"048c1197a0887c693689ce164b2ed030","url":"fonts/DMSans/DMSans-MediumItalic.ttf"},{"revision":"248753109983e15b95623c355e988c4d","url":"fonts/DMSans/DMSans-MediumItalic.woff"},{"revision":"b5d9a996963d8c9b27b19d8fd5cc4280","url":"fonts/DMSans/DMSans-MediumItalic.woff2"},{"revision":"d11e1ee7ca46d6142a64695512748b44","url":"fonts/DMSans/DMSans-Regular.eot"},{"revision":"79b04c84c6ed178b1e0d62f012966228","url":"fonts/DMSans/DMSans-Regular.svg"},{"revision":"b6df27b3572f418e24f220536f486b88","url":"fonts/DMSans/DMSans-Regular.ttf"},{"revision":"116ebf070a488224b3df4558d5e836b0","url":"fonts/DMSans/DMSans-Regular.woff"},{"revision":"7795a419ed60bbfac7070ea410eeae6a","url":"fonts/DMSans/DMSans-Regular.woff2"},{"revision":"1788e1b4395d153ef74296d34bef8be9","url":"fonts/index.css"},{"revision":"b66de1a7ecc3be2cd0ad2b85a429e303","url":"fonts/Inter/Inter-Black.eot"},{"revision":"0482d48f497a484ca329248e04d153ae","url":"fonts/Inter/Inter-Black.svg"},{"revision":"e072c0d33a83489dc304acd337fc25e1","url":"fonts/Inter/Inter-Black.ttf"},{"revision":"165563c4d60938a62db4e8e203419dcd","url":"fonts/Inter/Inter-Black.woff"},{"revision":"1b19574d075cd8d47035e3ffbb31e789","url":"fonts/Inter/Inter-Black.woff2"},{"revision":"efc914ba1b7bb7771fa19d126a18c6ef","url":"fonts/Inter/Inter-Bold.eot"},{"revision":"169351447569d6c8caf70d4d553b40fe","url":"fonts/Inter/Inter-Bold.svg"},{"revision":"c7222ea96badc2c78b1ad5964c5f3fb7","url":"fonts/Inter/Inter-Bold.ttf"},{"revision":"9864a52faa634aa3923aa8e18a66a447","url":"fonts/Inter/Inter-Bold.woff"},{"revision":"134108683a66c89f1af0f60bbdbf84c1","url":"fonts/Inter/Inter-Bold.woff2"},{"revision":"f59613daee5dc2ca3502c9ada5dba9fa","url":"fonts/Inter/Inter-ExtraBold.eot"},{"revision":"164513325572a2c692c80b9f3b0aec0b","url":"fonts/Inter/Inter-ExtraBold.svg"},{"revision":"b144c56b526e0e6d2886c53ef673cf53","url":"fonts/Inter/Inter-ExtraBold.ttf"},{"revision":"7041b83ed24a9cbf5c248c92347f2cd4","url":"fonts/Inter/Inter-ExtraBold.woff"},{"revision":"fa66016d8720d2e0c1dabbc6da9c0983","url":"fonts/Inter/Inter-ExtraBold.woff2"},{"revision":"24dffb71512ca8db35b8a709df38016a","url":"fonts/Inter/Inter-Medium.eot"},{"revision":"edb653710331c8f1908274aef36eeee7","url":"fonts/Inter/Inter-Medium.svg"},{"revision":"ff95fed28748c1bcb50177ff443e814b","url":"fonts/Inter/Inter-Medium.ttf"},{"revision":"a9041df04dc9b9ce3b4c14e708d5a728","url":"fonts/Inter/Inter-Medium.woff"},{"revision":"99a3c0889316e1e78077fc60bc3d468a","url":"fonts/Inter/Inter-Medium.woff2"},{"revision":"07bf7015e8a8293840ca696e7b88275d","url":"fonts/Inter/Inter-Regular.eot"},{"revision":"74526894722a9e30047191246456ced7","url":"fonts/Inter/Inter-Regular.svg"},{"revision":"bed1dd5f2dc75993805fbf445e23a6c3","url":"fonts/Inter/Inter-Regular.ttf"},{"revision":"678f9520fa54a52fb87f57e7efbabdef","url":"fonts/Inter/Inter-Regular.woff"},{"revision":"990ee43224d76dd50a936acaf489d0e4","url":"fonts/Inter/Inter-Regular.woff2"},{"revision":"4260b090187d3f7a73424a7a008414e3","url":"fonts/Inter/Inter-SemiBold.eot"},{"revision":"009828e685f7f78bf9a7b79e6eb0e086","url":"fonts/Inter/Inter-SemiBold.svg"},{"revision":"bb1398cc02de18ecb32d4a68f693f43e","url":"fonts/Inter/Inter-SemiBold.ttf"},{"revision":"d5d9d7641d430bf4e32a89ada03275d9","url":"fonts/Inter/Inter-SemiBold.woff"},{"revision":"304a147d58239ee4f2b451f1ac5979c2","url":"fonts/Inter/Inter-SemiBold.woff2"},{"revision":"d960b795b343e35150c1a0aa3c38c16b","url":"fonts/material-icons/material.woff2"},{"revision":"2f1737e005052d987be69772f1e9887e","url":"locales/en.json"},{"revision":"99914b932bd37a50b983c5e7c90ae93b","url":"locales/you need to add customer!.json"}]);
precacheAndRoute(self.__WB_MANIFEST);
// tslint:disable-next-line

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith("/_")) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-provider .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Any other custom service worker logic can go here.
