FROM node:12.21-alpine as builder

ARG REACT_APP_API_BASE_URL
ARG REACT_APP_STRIPE_PRIVATE_KEY
ARG SKIP_PREFLIGHT_CHECK
ARG REACT_APP_S3_MEDIA
ARG REACT_APP_GOOGLE_MAP_URL
ARG REACT_APP_GOOGLE_MAP_API_KEY
ARG REACT_APP_GOOGLE_MAP_GEOCODING_URL
ARG REACT_APP_API_WS_URL

WORKDIR /root/app

COPY . .

RUN npm install
RUN printenv
RUN npm run build:admin

# ----------------------------------------------------------------------------
FROM nginx:1.16.1-alpine

RUN rm -f /etc/nginx/conf.d/default.conf && \
    printf " \
server { \n \
    listen       80; \n \
    listen  [::]:80; \n \
    client_max_body_size 20M; \n \
    server_name _ default_server; \n \
    root /usr/share/nginx/html; \n \
    location / { \n \
        root      /usr/share/nginx/html; \n \
        try_files \$uri \$uri/ /index.html; \n \
    } \n \
}" >> /etc/nginx/conf.d/default.conf

COPY --from=builder /root/app/build-admin /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]
