export const HISTORY = "HISTORY";

export const AUTH_REPOSITORY = "AUTH_REPOSITORY";
export const AUTH_SERVICE = "AUTH_SERVICE";

export const SESSION_USER_REPOSITORY = "SESSION_USER_REPOSITORY";
export const SESSION_USER_SERVICE = "SESSION_USER_SERVICE";

export const CAR_REPOSITORY = "CAR_REPOSITORY";
export const CAR_SERVICE = "CAR_SERVICE";

export const EDIT_CAR_REPOSITORY = "EDIT_CAR_REPOSITORY";
export const EDIT_CAR_SERVICE = "EDIT_CAR_SERVICE";

export const LOCK_CAR_REPOSITORY = "LOCK_CAR_REPOSITORY";
export const LOCK_CAR_SERVICE = "LOCK_CAR_SERVICE";

export const NEW_CAR_REPOSITORY = "NEW_CAR_REPOSITORY";
export const NEW_CAR_SERVICE = "NEW_CAR_SERVICE";

export const CARS_REPOSITORY = "CARS_REPOSITORY";
export const CARS_SERVICE = "CARS_SERVICE";

export const MEDIA_REPOSITORY = "MEDIA_REPOSITORY";
export const MEDIA_SERVICE = "MEDIA_SERVICE";

export const RESERVATIONS_REPOSITORY = "RESERVATIONS_REPOSITORY";
export const RESERVATIONS_SERVICE = "RESERVATIONS_SERVICE";

export const ADD_NEW_CUSTOMER_REPOSITORY = "ADD_NEW_CUSTOMER_REPOSITORY";
export const ADD_NEW_CUSTOMER_SERVICE = "ADD_NEW_CUSTOMER_SERVICE";

export const CUSTOMER_REPOSITORY = "CUSTOMER_REPOSITORY";
export const CUSTOMER_SERVICE = "CUSTOMER_SERVICE";

export const CUSTOMERS_REPOSITORY = "CUSTOMERS_REPOSITORY";
export const CUSTOMERS_SERVICE = "CUSTOMERS_SERVICE";

export const MY_RESERVATIONS_REPOSITORY = "MY_RESERVATIONS_REPOSITORY";
export const MY_RESERVATIONS_SERVICE = "MY_RESERVATIONS_SERVICE";

export const PAYMENT_REPOSITORY = "PAYMENT_REPOSITORY";
export const PAYMENT_SERVICE = "PAYMENT_SERVICE";

export const RESERVATION_REPOSITORY = "RESERVATION_REPOSITORY";
export const RESERVATION_SERVICE = "RESERVATION_SERVICE";

export const DASHBOARD_REPOSITORY = "DASHBOARD_REPOSITORY";
export const DASHBOARD_SERVICE = "DASHBOARD_SERVICE";

export const ADD_NEW_RESERVATION_BY_ADMIN_REPOSITORY = "ADD_NEW_RESERVATION_BY_ADMIN_REPOSITORY";
export const ADD_NEW_RESERVATION_BY_ADMIN_SERVICE = "ADD_NEW_RESERVATION_BY_ADMIN_SERVICE";

export const NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE";

export const NOTIFICATIONS_LIST_SERVICE = "NOTIFICATIONS_LIST_SERVICE";
export const NOTIFICATIONS_LIST_REPOSITORY = "NOTIFICATIONS_LIST_REPOSITORY";

export const EXCEPTION_SERVICE = "EXCEPTION_SERVICE";

export const APP_SERVICE = "APP_SERVICE";

export const THANK_YOU_SERVICE = "THANK_YOU_SERVICE";

export const SIDEBAR_SERVICE = "SIDEBAR_SERVICE";

export const DRONE_MOBILE_REPOSITORY = "DRONE_MOBILE_REPOSITORY";
export const DRONE_MOBILE_SERVICE = "DRONE_MOBILE_SERVICE";

export const WS_API = "WS_API";

export const SOCKETS_SERVICE = "SOCKETS_SERVICE";
export const SOCKETS_REPOSITORY = "SOCKETS_REPOSITORY";
